### ISSUE TITLE
Google Sheets API has changed

### ISSUE THREAD

**Issue by BagiSenior** [code4recovery/online-meeting-list#17]
RE: https://online-meeting-list.netlify.app/
Looks like Google change something and a simple way to expose google sheets as JSON does not work - the page got stuck at loading, 404 error when checking the log details (same when pasting the URL into the address bar)
I have tried to google the solution - looks like the old way of exporting the data as JSON has been depreciated together with v3 of google sheets API. Any chance to find a workaround and/or re-do for google sheets API v4? (most likely including OAth2.0/API key solution)
![image](https://user-images.githubusercontent.com/77568181/129866091-cb30e5d1-20fe-4b2a-991f-fee4b58d22a8.png)

**Comment by tintinnabulate** [comment]
@BagiSenior Yes, I have noticed this also. I'm investigating a workaround/solution.

**Comment by tintinnabulate** [comment]
My site uses netlify to build and publish the site. Until I can find a solution, I've created a redirect to the raw HTML spreadsheet:

filename `netlify.toml`:

```
[[redirects]]
  from = "/"
  to = "https://aa-intergroup.org/meetings"
  status = 302
  force = true
  headers = {X-From = "Netlify"}
```

Described here: <https://docs.netlify.com/configure-builds/file-based-configuration/#redirects>

**Comment by joshreisner** [comment]
It's great that you figured out the issue - it completely took me by surprise when Google rolled out the change on Thursday.

What used to be in this URL format:
`https://spreadsheets.google.com/feeds/list/<SHEET_ID>/1/public/values?alt=json`

Has now changed to this:
`https://sheets.googleapis.com/v4/spreadsheets/<SHEET_ID>/values/<RANGE>?key=<API_KEY>`

And the data it gets back is a different shape (seems cleaner to me now).

I'm not really sure what to do - the new v4 script requires an API key which seems like a) a barrier to people using the service and b) not a good idea to publish publicly

I developed a temporary stopgap for Online Intergroup - a PHP script that you trigger manually to generate a static JSON file. It means that once he's done editing, the OIAA meeting coordinator visits a URL to publish the changes.

On the positive side, this system enables a kind of draft mode when they're editing.

OIAA is coincidentally planning to move away from Google sheets entirely, hopefully they can be persuaded to open source the solution they're developing.

**Comment by BagiSenior** [comment]
> It's great that you figured out the issue - it completely took me by surprise when Google rolled out the change on Thursday.
> 
> What used to be in this URL format:
> `https://spreadsheets.google.com/feeds/list/<SHEET_ID>/1/public/values?alt=json`
> 
> Has now changed to this:
> `https://sheets.googleapis.com/v4/spreadsheets/<SHEET_ID>/values/<RANGE>?key=<API_KEY>`
> 
> And the data it gets back is a different shape (seems cleaner to me now).
> 
> I'm not really sure what to do - the new v4 script requires an API key which seems like a) a barrier to people using the service and b) not a good idea to publish publicly
> 
> I developed a temporary stopgap for Online Intergroup - a PHP script that you trigger manually to generate a static JSON file. It means that once he's done editing, the OIAA meeting coordinator visits a URL to publish the changes.
> 
> On the positive side, this system enables a kind of draft mode when they're editing.
> 
> OIAA is coincidentally planning to move away from Google sheets entirely, hopefully they can be persuaded to open source the solution they're developing.

@joshreisner any chance you can share the PHP script so we can use the same? We are having all data of meetings inside SFDC, with automatic synchro every few hours (SFDC plugin) now need to convert to JSON manually. If you have a structure/example of "old" JSON, as it used to be, would be great as well - maybe we will just extract the data from SFDC directly. Thx in advance.

**Comment by joshreisner** [comment]
Sure I am working on a Laravel app that does a bunch of things related to sheets but here are the lines for OIAA:

```php
Route::get('oiaa', function () {


    //fetch data
    $rows = Http::get(
        'https://sheets.googleapis.com/v4/spreadsheets/' .
            env('GOOGLE_SHEET_ID') . '/values/A1:Z10000?key=' .
            env('GOOGLE_SHEET_API_KEY')
    )['values'];


    //get columns
    $columns = array_map(function ($column) {
        return Str::slug($column, '_');
    }, array_shift($rows));
    $column_count = count($columns);


    //remove empty rows
    $rows = array_filter($rows, function ($row) {
        return strlen($row[0]);
    });


    //loop through and format rows
    $rows = array_map(function ($row) use ($columns, $column_count) {
        $row = array_map('trim', $row);
        extract(array_combine($columns, array_pad($row, $column_count, null)));
        return compact('name', 'times', 'timezone', 'url', 'phone', 'access_code', 'email', 'types', 'formats', 'notes');
    }, $rows);


    Storage::disk('public')->put('oiaa.json', json_encode($rows));


    return 'done!';
});
```

The JSON format which used to [look like this](https://aa-intergroup.org/wp-content/values.json) now [looks like this](https://sheets.code4recovery.org/storage/oiaa.json).

The new format required some code changes to the meeting finder which I [stashed in this draft PR](https://github.com/code4recovery/online-meeting-list/pull/18).

**Comment by tintinnabulate** [comment]
> It's great that you figured out the issue - it completely took me by surprise when Google rolled out the change on Thursday.
> 
> What used to be in this URL format:
> `https://spreadsheets.google.com/feeds/list/<SHEET_ID>/1/public/values?alt=json`
> 
> Has now changed to this:
> `https://sheets.googleapis.com/v4/spreadsheets/<SHEET_ID>/values/<RANGE>?key=<API_KEY>`
> 
> And the data it gets back is a different shape (seems cleaner to me now).
> 
> I'm not really sure what to do - the new v4 script requires an API key which seems like a) a barrier to people using the service and b) not a good idea to publish publicly
Netlify allows you to have secrets on the account, so that's an option.
> 
> I developed a temporary stopgap for Online Intergroup - a PHP script that you trigger manually to generate a static JSON file. It means that once he's done editing, the OIAA meeting coordinator visits a URL to publish the changes.
> 
> On the positive side, this system enables a kind of draft mode when they're editing.
> 
> OIAA is coincidentally planning to move away from Google sheets entirely, hopefully they can be persuaded to open source the solution they're developing.

**Comment by joshreisner** [comment]
> Netlify allows you to have secrets on the account, so the API key could be stored there, and thus not published publicly. 

That's a good point but you'd need to also use lambda functions. That would be a good solution for sites hosted on Netlify. (OIAA is not.)

**Comment by BagiSenior** [comment]
> Netlify allows you to have secrets on the account, so the API key could be stored there, and thus not published publicly.

Netlify solution with "secrets" would be a great workaround......

**Comment by tintinnabulate** [comment]
> > Netlify allows you to have secrets on the account, so the API key could be stored there, and thus not published publicly. 
> 
> That's a good point but you'd need to also use lambda functions. That would be a good solution for sites hosted on Netlify. (OIAA is not.)

I don't quite understand this. What are lambda functions?

Do you mean these: <https://www.netlify.com/blog/2020/10/29/announcing-background-functions/> ?

**Comment by joshreisner** [comment]
I've added support  for Sheets API `v4` in #18 

You will need to add a `REACT_APP_GOOGLE_API_KEY` environment variable (through Netlify or in your `.env` file) in addition to the `REACT_APP_GOOGLE_SHEET` you already have. (This API key will need Sheets API permission, see README.md)

[Netlify Functions](https://www.netlify.com/products/functions/), or something similar, are what you will need if you want to conceal your API key from the public.

**Comment by BagiSenior** [comment]
@joshreisner thank you a million!
There is one point to be sorted out still - it's very easy to intercept the API key directly from a browser by checking network traffic in the browser (inspect -> network in Chrome). Maybe we should consider extending the solution with a backend proxy-like function that will be providing JSON without disclosing the API KEY in any way? WDYF?

**Comment by joshreisner** [comment]
@BagiSenior yes that's exactly what i was just saying when I wrote

> Netlify Functions, or something similar, are what you will need if you want to conceal your API key from the public.

That's going to be up to individual website to figure out. I added another option for loading a JSON feed, which is documented in the readme

**Comment by BagiSenior** [comment]
> @BagiSenior yes that's exactly what i was just saying when I wrote
> 
> > Netlify Functions, or something similar, are what you will need if you want to conceal your API key from the public.
> 
> That's going to be up to individual website to figure out. I added another option for loading a JSON feed, which is documented in the readme

@joshreisner - clear - thank you for that - I did not notice amended readme file :-)

What we have implemented as a solution (maybe will be helpful for somebody) is a cron job running every 5 min, getting a JSON and storing it in the readable folder on a webpage. To the best of my knowledge cron is available at the majority of hosting sites, sometimes even with a graphical interface like cPanel (used by my provider). One liner like:
`curl -v 'https://sheets.googleapis.com/v4/spreadsheets/<SPREADSHEET_LINK>/values/<SHEET_NAME>!A1:Z10000?key=<GOOGLE_API_KEY' --output /home/<USER>/public_html/<FOLDER_READABLE>/wa.json`

**Comment by tintinnabulate** [comment]
> I've added support  for Sheets API `v4` in #18 
> 
> You will need to add a `REACT_APP_GOOGLE_API_KEY` environment variable (through Netlify or in your `.env` file) in addition to the `REACT_APP_GOOGLE_SHEET` you already have. (This API key will need Sheets API permission, see README.md)
> 
> [Netlify Functions](https://www.netlify.com/products/functions/), or something similar, are what you will need if you want to conceal your API key from the public.

Amazing. Thanks!
