### ISSUE TITLE
Json update not pushing

### ISSUE THREAD

**Issue by csrcarlson** [code4recovery/online-meeting-list#29]
It seems when script is run, the data is not being pushed (json data changes not appearing to be applied to site)

We make changes to google spreadsheet, run https://sheets.code4recovery.org/oiaa but changes are not showing up.

Tom - March 10 - 10PM MST

**Comment by joshreisner** [comment]
hi @csrcarlson could you give an example of a specific data point thats not syncing up?

assuming this just started happening recently?

**Comment by joshreisner** [comment]
looks like the oiaa.json file was last modified at 9:56pm MT, so looks like at least some amount of data is getting fetched and saved

**Comment by joshreisner** [comment]
@csrcarlson we need more info from you to know what problems to look for, thanks

**Comment by csrcarlson** [comment]
I think it was a lag. I changed a few records and they appear to be updated now. I will keep checking and see, but I think we are good now. Weird...

**Comment by joshreisner** [comment]
ok great
