### ISSUE TITLE
Uppercase Search is Returning No Results

### ISSUE THREAD

**Issue by mattbylett** [code4recovery/online-meeting-list#36]
Hi,

I recently had to roll back to a clean install of the repo and whats happening is when I search with uppercase letters I get no results.

Steps to re-create

- git clone
- npm install
- create .env with Json Link (OIAA)
- npm build
- upload to site
- Search not optimal

<img width="1350" alt="Screenshot 2022-09-05 at 8 58 02 AM" src="https://user-images.githubusercontent.com/31151177/188333372-5c60cff6-cfc1-4b5f-998e-054ef195c3aa.png">
<img width="1347" alt="Screenshot 2022-09-05 at 8 58 12 AM" src="https://user-images.githubusercontent.com/31151177/188333376-cb9f48aa-5c55-4ff1-836d-5c1f64f75b3a.png">

Any idea what could be causing this?

**Comment by joshreisner** [comment]
oops, thanks for the bug report matt! should be fixed now

**Comment by mattbylett** [comment]
Sweet Cheers Josh - I hope that was the right place to do it - seemed to be
separate from our thread so thought it was the right thing to do

Appreciate you looking into it on Sunday - I'll re-pull now and check it out

Have a great day

Matt

**Comment by mattbylett** [comment]
Perfect 👍   Works a treat

Thank you Josh
