### ISSUE TITLE
Need 2 new languages added 

### ISSUE THREAD

**Issue by KMRDRIVE** [code4recovery/online-meeting-list#59]
We have 2 new languages that need to be added to the online meeting selection. 

Maltese and Nepali 

Please advise when complete.  Thank you so much for your service. 

Keri

**Comment by joshreisner** [comment]
hi @KMRDRIVE are you representing OIAA? do you need the codes added to central as well?

**Comment by KMRDRIVE** [comment]
Hi
Yes. OIAA. I am on the technology committee and also OIAA tech steppers.  I’ve been doing the directory updates for a while since before the new directory.
And yes, we need it in Central to be able to enter the meeting and also the directory page to filter.
Thanks so much
Keri

Keri Roche
***@***.***

________________________________

**Comment by joshreisner** [comment]
ok sounds good! 

@mattbylett got two PRs for you to review and deploy ☝️

**Comment by joshreisner** [comment]
@KMRDRIVE you should be good to add the meeting types now in central - once matt merges and deploys the other PR we can see if it worked ;)

**Comment by joshreisner** [comment]
sounds like there was a hiccup deploying, but i'm pretty certain the code is working as expected. going to close the issue, but feel free to follow up if i can help at all.

**Comment by mattbylett** [comment]
Thanks Josh - I’ll check it tomorrow when I’m fresh

Appreciate you :)

We help businesses develop integrated ecommerce digital solutions

Matthew Bylett
Founder Think New Ltd
022 029 2881
