### ISSUE TITLE
New language to be added

### ISSUE THREAD

**Issue by twn2twn** [code4recovery/online-meeting-list#62]
Hi, we have a request to add Bulgarian to languages. 
Please let me know when it is live. thank you for this, Jeff B

**Comment by twn2twn** [comment]
Hey Josh,
Yes, I'll include it next time. thank you, Jeff B

**Comment by joshreisner** [comment]
all good thanks! i'll let you know when they are added

**Comment by joshreisner** [comment]
ok i've added the language to central now, do you see the checkbox?
