### ISSUE TITLE
Google "&" anomalies

### ISSUE THREAD

**Issue by twn2twn** [code4recovery/online-meeting-list#63]
Hi, 
We've had the issue of forms submitted through the site coming across with some anomalies. 
When "&" is added, it comes across as "&amp,". Can this be corrected? 
thank you, Jeff B

**Comment by joshreisner** [comment]
could you link me to one of these forms? my guess is this is not related to the meetings software and is a job for the web servant but this will help me know for sure

**Comment by joshreisner** [comment]
yep these are handled by the web servant are probably a plugin called [WPForms](https://wpforms.com/)

going to tag @mattbylett and close 👍
