### ISSUE TITLE
Is this an issue?

### ISSUE THREAD

**Issue by twn2twn** [code4recovery/online-meeting-list#64]
I'd entered a new meeting in Central. I only completed the main / group page, then refreshed Json. 

I'm waiting to hear from Josh about Bulgarian being added as a language before I actually add the meetings. 

When I enter the OIMN in the search, no results. I copy and paste the full or partial name of the group, no results
When I click on 'Groups', and can see the name of the Group in the listing, click on it and view the name group page with correct OIMN. 

Does it somehow need a meeting listed to bring this up?
If so, can this be fixed easily? Or is it 'just not like that'?
thanks, Jeff B

**Comment by joshreisner** [comment]
are you searching on the frontend, or in central? i would expect the group with no meetings to come up in central but not in online meeting list

that said, searching in central seems to be erratic, and needs more investigation. i opened an issue here about it https://github.com/code4recovery/central/issues/11

i don't have any bandwidth for the next two weeks or so, not sure if there are any other code for recovery members who can help out?

**Comment by twn2twn** [comment]
In Central

**Comment by joshreisner** [comment]
ok - since we're already tracking this issue in https://github.com/code4recovery/central/issues/11 i'm going to close this one, but if you notice any patterns in what works and what doesn't please leave a comment there, thanks
