### ISSUE TITLE
Phone String

### ISSUE THREAD

**Issue by twn2twn** [code4recovery/online-meeting-list#72]
Hi, 
Jeff OIAA - 

I was under the impression the 'conference URL' had the phone string format  - 

PhoneNumber,,ZoomID#,,Passcode#

My laptop can't dial out, but when I use the PHONE button from the site on my phone, it displays all number together without the symbols and doesn't work. 

This is how most all 'one touch' dial ins were set up and I followed suit. Is this not correct? If correct, how can it be made to work?
thank you

**Comment by joshreisner** [comment]
@mattbylett if you could pull and redeploy this issue should be fixed now ✅

**Comment by mattbylett** [comment]
Thanks Josh - will do 👌

We help businesses develop integrated ecommerce digital solutions

Matthew Bylett
Founder Think New Ltd
022 029 2881

**Comment by mattbylett** [comment]
Pulled and deployed - ready for testing

**Comment by joshreisner** [comment]
thanks @mattbylett !

@twn2twn let us know if that fixes it or if not what meeting to test it on, thanks

**Comment by twn2twn** [comment]
Works for me! thank you both, Jeff B
